Repository adopted-ember-addons/ember-popper-modifier, pull requests merged in 2023-01, with the labels that each got.

#578 drop support for Ember < 3.28
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#577 drop support for node < 14 and other node versions reached EOL
  README.md
  package.json
Labels: breaking

#581 Support releases and changelog generation using release-it
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#587 use standard Prettier configuration in Ember ecosystem
  .eslintrc.js
  .github/dependabot.yml
  .prettierrc.js
  .template-lintrc.js
  addon/-base-popper-modifier.js
  addon/helpers/popper-modifier.js
  addon/in-runloop-modifier.js
  addon/index.js
  addon/modifiers/popper-tooltip.js
  addon/modifiers/popper.js
  app/helpers/popper-modifier.js
  app/modifiers/popper-tooltip.js
  app/modifiers/popper.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  testem.js
  tests/assertions/comparisons.js
  tests/assertions/dom.js
  tests/assertions/testdouble.js
  tests/assertions/wait-for.js
  tests/dummy/app/app.js
  tests/dummy/app/components/with-tool-tip.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/integration/components/cookbook/tool-tip-test.js
  tests/integration/modifiers/popper-test.js
  tests/integration/modifiers/popper-tooltip-test.js
  tests/test-helper.js
  tests/unit/helpers/popper-modifier-test.js
Labels: internal

#592 upgrade boilerplate files with Ember CLI 4.9 blueprints
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.js
  .template-lintrc.js
  CONTRIBUTING.md
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  vendor/.gitkeep
  yarn.lock
Labels: internal

#508 Refactor to use ember-modifier's modify hook and fix deprecation
  addon/-base-popper-modifier.js
  addon/modifiers/popper-tooltip.js
  addon/modifiers/popper.js
  package.json
  yarn.lock
Labels: enhancement

#594 support ember-modifier v4
  package.json
  yarn.lock
Labels: enhancement

#595 add basic example in dummy app for manual testing
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/tool-tip.hbs
  tests/dummy/app/templates/components/with-tool-tip.hbs
  tests/dummy/app/templates/index.hbs
Labels: internal
